#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : Gradio
Version  : 7.2
Release  : 1
URL      : https://github.com/haecker-felix/Gradio/archive/v7.2.tar.gz
Source0  : https://github.com/haecker-felix/Gradio/archive/v7.2.tar.gz
Summary  : A GTK3 app for finding and listening to internet radio stations
Group    : Development/Tools
License  : GPL-3.0
Requires: Gradio-bin = %{version}-%{release}
Requires: Gradio-data = %{version}-%{release}
Requires: Gradio-license = %{version}-%{release}
Requires: Gradio-locales = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gstreamer-dev
BuildRequires : json-glib-dev
BuildRequires : libsoup-dev
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-pbutils-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : vala

%description
# Gradio
A GTK3 app for finding and listening to internet radio stations.
___
=> [Rust port / development here](https://github.com/haecker-felix/Gradio/tree/rust_port)
___

%package bin
Summary: bin components for the Gradio package.
Group: Binaries
Requires: Gradio-data = %{version}-%{release}
Requires: Gradio-license = %{version}-%{release}

%description bin
bin components for the Gradio package.


%package data
Summary: data components for the Gradio package.
Group: Data

%description data
data components for the Gradio package.


%package license
Summary: license components for the Gradio package.
Group: Default

%description license
license components for the Gradio package.


%package locales
Summary: locales components for the Gradio package.
Group: Default

%description locales
locales components for the Gradio package.


%prep
%setup -q -n Gradio-7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562691965
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --prefix /usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/Gradio
cp LICENSE.md %{buildroot}/usr/share/package-licenses/Gradio/LICENSE.md
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gradio

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gradio

%files data
%defattr(-,root,root,-)
/usr/share/appdata/de.haeckerfelix.gradio.appdata.xml
/usr/share/applications/de.haeckerfelix.gradio.desktop
/usr/share/dbus-1/services/de.haeckerfelix.gradio.service
/usr/share/glib-2.0/schemas/de.haeckerfelix.gradio.gschema.xml
/usr/share/gnome-shell/search-providers/de.haeckerfelix.gradio.search-provider.ini
/usr/share/icons/hicolor/16x16/apps/de.haeckerfelix.gradio.png
/usr/share/icons/hicolor/24x24/apps/de.haeckerfelix.gradio.png
/usr/share/icons/hicolor/256x256/apps/de.haeckerfelix.gradio.png
/usr/share/icons/hicolor/32x32/apps/de.haeckerfelix.gradio.png
/usr/share/icons/hicolor/48x48/apps/de.haeckerfelix.gradio.png
/usr/share/icons/hicolor/512x512/apps/de.haeckerfelix.gradio.png
/usr/share/icons/hicolor/scalable/apps/de.haeckerfelix.gradio.svg
/usr/share/icons/hicolor/symbolic/apps/de.haeckerfelix.gradio-symbolic.svg

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/Gradio/LICENSE.md

%files locales -f gradio.lang
%defattr(-,root,root,-)

